package WD.works.V2.usuario.auth.permissao;

public enum Permissao {

    // Empresa
    EMPRESA_VISUALIZAR,
    EMPRESA_EDITAR,


    // Usuário
    USUARIO_CRIAR,
    USUARIO_VISUALIZAR,
    USUARIO_EDITAR,
    USUARIO_BLOQUEAR,

    // Alertas de Stock
    ALERTA_STOCK_VISUALIZAR,

    // Produto
    PRODUTO_CRIAR,
    PRODUTO_VISUALIZAR,
    PRODUTO_EDITAR,
    PRODUTO_DESATIVAR,
    PRODUTO_ATIVAR,

    // Categoria
    CATEGORIA_CRIAR,
    CATEGORIA_VISUALIZAR,
    CATEGORIA_EDITAR,
    CATEGORIA_EXCLUIR,

    // Venda
    VENDA_CRIAR,
    VENDA_VISUALIZAR,
    VENDA_CANCELAR,

    // Estoque
    ESTOQUE_VISUALIZAR,
    ESTOQUE_AJUSTAR,
    ESTOQUE_MOVIMENTAR,

    // Auditoria
    AUDITORIA_VISUALIZAR,

    //Dashboard
    DASHBOARD_VISUALIZAR
}